<a href="https://colab.research.google.com/github/tanvitalari/Git-Projects/blob/main/datascience_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Array Operations

**Question 1**

In [ ]:
import random
import math

array = [[random.randint(0, 10) for _ in range(3)] for _ in range(3)] # Create 3x3 array

total = 0
count = 0
for row in array:
    for val in row:
        total += val
        count += 1

mean = total / count #mean

sq_diff_sum = 0
for row in array:
    for val in row:
        sq_diff_sum += (val - mean) ** 2

std_dev = math.sqrt(sq_diff_sum / count) #standard deviation

print("3x3 Array:")
for row in array:
    print(row)

print("\nSum:", total)
print("Mean:", mean)
print("Standard Deviation:", std_dev)


3x3 Array:
[1, 9, 2]
[7, 8, 4]
[3, 6, 2]

Sum: 42
Mean: 4.666666666666667
Standard Deviation: 2.748737083745107


**Question 2**

In [ ]:
import random

arr = [random.randint(0, 20) for _ in range(10)] # create 1D array

cumulative_sum = [] # cumulative sum
running_total = 0

for val in arr:
    running_total += val
    cumulative_sum.append(running_total)

print("Original Array:", arr)
print("Cumulative Sum:", cumulative_sum)


Original Array: [14, 0, 12, 6, 17, 5, 19, 4, 20, 9]
Cumulative Sum: [14, 14, 26, 32, 49, 54, 73, 77, 97, 106]


**Question 3**

In [ ]:
import random

A = [[random.randint(1, 10) for _ in range(3)] for _ in range(2)] #Generate two 2x3 arrays
B = [[random.randint(1, 10) for _ in range(3)] for _ in range(2)]

add_result = [[0]*3 for _ in range(2)]
sub_result = [[0]*3 for _ in range(2)]
mul_result = [[0]*3 for _ in range(2)]
div_result = [[0]*3 for _ in range(2)]

for i in range(2): # element wise operations
    for j in range(3):
        add_result[i][j] = A[i][j] + B[i][j]
        sub_result[i][j] = A[i][j] - B[i][j]
        mul_result[i][j] = A[i][j] * B[i][j]
        div_result[i][j] = A[i][j] / B[i][j]

print("Array A:", A)
print("Array B:", B)

print("\nElement-wise Addition:", add_result)
print("Element-wise Subtraction:", sub_result)
print("Element-wise Multiplication:", mul_result)
print("Element-wise Division:", div_result)


Array A: [[2, 7, 1], [4, 10, 8]]
Array B: [[8, 7, 7], [5, 9, 10]]

Element-wise Addition: [[10, 14, 8], [9, 19, 18]]
Element-wise Subtraction: [[-6, 0, -6], [-1, 1, -2]]
Element-wise Multiplication: [[16, 49, 7], [20, 90, 80]]
Element-wise Division: [[0.25, 1.0, 0.14285714285714285], [0.8, 1.1111111111111112, 0.8]]


**Question 4**

In [ ]:
identity_matrix = [[0 for _ in range(4)] for _ in range(4)] # 4x4 matrix

for i in range(4):
    identity_matrix[i][i] = 1

print("4x4 Identity Matrix:")
for row in identity_matrix:
    print(row)


4x4 Identity Matrix:
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


**Question 5**

In [ ]:
import numpy as np

a = np.array([5, 10, 15, 20, 25]) # Create array

result = a / 5

print("Original Array:", a)
print("Result after dividing by 5:", result)


Original Array: [ 5 10 15 20 25]
Result after dividing by 5: [1. 2. 3. 4. 5.]


# Array Manipulation

**Question 6**

In [ ]:
import numpy as np

a = np.array([i for i in range(1, 13)])  # [1, 2, ..., 12]

rows, cols = 3, 4
matrix = []

index = 0
for i in range(rows):
    row = []
    for j in range(cols):
        row.append(a[index])
        index += 1
    matrix.append(row)

print("Original 1D Array:", a)
print("\nReshaped 3x4 Matrix:")
for row in matrix:
    print(row)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 Matrix:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
[np.int64(5), np.int64(6), np.int64(7), np.int64(8)]
[np.int64(9), np.int64(10), np.int64(11), np.int64(12)]


**Question 7**

In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

flattened = []
for row in matrix:
    for val in row:
        flattened.append(val)

print("Original 3x3 Matrix:")
for row in matrix:
    print(row)

print("\nFlattened 1D Array:", flattened)


Original 3x3 Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Flattened 1D Array: [1, 2, 3, 4, 5, 6, 7, 8, 9]


**Question 8**

In [ ]:
A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

B = [
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
]

horizontal_stack = []
for i in range(len(A)):
    horizontal_stack.append(A[i] + B[i])

vertical_stack = A + B

print("Matrix A:")
for row in A:
    print(row)

print("\nMatrix B:")
for row in B:
    print(row)

print("\nHorizontal Stack (3x6):")
for row in horizontal_stack:
    print(row)

print("\nVertical Stack (6x3):")
for row in vertical_stack:
    print(row)


Matrix A:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix B:
[10, 11, 12]
[13, 14, 15]
[16, 17, 18]

Horizontal Stack (3x6):
[1, 2, 3, 10, 11, 12]
[4, 5, 6, 13, 14, 15]
[7, 8, 9, 16, 17, 18]

Vertical Stack (6x3):
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]
[13, 14, 15]
[16, 17, 18]


**Question 9**

In [ ]:
A = [1, 2, 3]
B = [4, 5, 6, 7, 8]

C = [A, B]

print("Array A:", A)
print("Array B:", B)
print("\nConcatenated along new axis:")
for row in C:
    print(row)


Array A: [1, 2, 3]
Array B: [4, 5, 6, 7, 8]

Concatenated along new axis:
[1, 2, 3]
[4, 5, 6, 7, 8]


**Question 10**

In [ ]:
matrix = [
    [1, 2],
    [3, 4],
    [5, 6]
]

transpose = []
for j in range(len(matrix[0])):
    row = []
    for i in range(len(matrix)):
        row.append(matrix[i][j])
    transpose.append(row)

flat = []
for row in transpose:
    for val in row:
        flat.append(val)

reshaped = []
index = 0
for i in range(3):
    row = []
    for j in range(2):
        row.append(flat[index])
        index += 1
    reshaped.append(row)

print("Original 3x2 Matrix:")
for row in matrix:
    print(row)

print("\nTransposed (2x3 Matrix):")
for row in transpose:
    print(row)

print("\nReshaped back to 3x2:")
for row in reshaped:
    print(row)


Original 3x2 Matrix:
[1, 2]
[3, 4]
[5, 6]

Transposed (2x3 Matrix):
[1, 3, 5]
[2, 4, 6]

Reshaped back to 3x2:
[1, 3]
[5, 2]
[4, 6]


# Indexing and Slicing

**Question 11**

In [1]:
arr = [i for i in range(1, 16)]

start, end, step = 2, 10, 2
extracted = []

i = start
while i < end:
    extracted.append(arr[i])
    i += step

print("Original Array:", arr)
print("Extracted Elements (positions 2 to 10, step 2):", extracted)


Original Array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Extracted Elements (positions 2 to 10, step 2): [3, 5, 7, 9]


**Question 12**

In [2]:
matrix = []
val = 1
for i in range(5):
    row = []
    for j in range(5):
        row.append(val)
        val += 1
    matrix.append(row)

start_row, end_row = 1, 3
start_col, end_col = 2, 4

sub_matrix = []
for i in range(start_row, end_row + 1):
    row = []
    for j in range(start_col, end_col + 1):
        row.append(matrix[i][j])
    sub_matrix.append(row)

print("Original 5x5 Matrix:")
for row in matrix:
    print(row)

print("\nExtracted Sub-Matrix (rows 1–3, cols 2–4):")
for row in sub_matrix:
    print(row)

Original 5x5 Matrix:
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

Extracted Sub-Matrix (rows 1–3, cols 2–4):
[8, 9, 10]
[13, 14, 15]
[18, 19, 20]


**Question 13**

In [3]:
arr = [1, 3, 11, 13, 7, 30, 9, 18]

for i in range(len(arr)):
    if arr[i] > 10:
        arr[i] = 10

print(arr)


[1, 3, 10, 10, 7, 10, 9, 10]


**Question 14**

In [4]:
arr = [10, 20, 30, 40, 50, 60, 70, 80]

indices = [0, 2, 4, 6]

selected_elements = [arr[i] for i in indices]

print(selected_elements)


[10, 30, 50, 70]


**Question 15**

In [5]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

reversed_arr = arr[::-1]

print(reversed_arr)


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


# Broadcasting

**Question 16**

In [6]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr = [10, 20, 30]

result = []
for row in matrix:
    new_row = []
    for i in range(len(row)):
        new_row.append(row[i] + arr[i])
    result.append(new_row)

print(result)


[[11, 22, 33], [14, 25, 36], [17, 28, 39]]


**Question 17**

In [7]:
arr = [2, 4, 6, 8, 10]

scalar = 3

result = []
for i in range(len(arr)):
    result.append(arr[i] * scalar)

print(result)


[6, 12, 18, 24, 30]


**Question 18**

In [8]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

col_vector = [1, 2, 3]

result = []
for i in range(len(matrix)):
    new_row = []
    for j in range(len(matrix[i])):
        new_row.append(matrix[i][j] - col_vector[i])
    result.append(new_row)

print(result)


[[0, 1, 2], [2, 3, 4], [4, 5, 6]]


**Question 19**

In [9]:
array_3d = [
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]

scalar = 10

result = []
for i in range(len(array_3d)):
    new_matrix = []
    for j in range(len(array_3d[i])):
        new_row = []
        for k in range(len(array_3d[i][j])):
            new_row.append(array_3d[i][j][k] + scalar)
        new_matrix.append(new_row)
    result.append(new_matrix)

print(result)


[[[11, 12], [13, 14]], [[15, 16], [17, 18]]]


**Question 20**

In [10]:
arr1 = [
    [1],
    [2],
    [3],
    [4]
]

arr2 = [
    [10, 20, 30, 40, 50]
]

result = []
for i in range(len(arr1)):
    new_row = []
    for j in range(len(arr2[0])):
        new_row.append(arr1[i][0] + arr2[0][j])
    result.append(new_row)

print(result)


[[11, 21, 31, 41, 51], [12, 22, 32, 42, 52], [13, 23, 33, 43, 53], [14, 24, 34, 44, 54]]


# Vectorized Operations

**Question 21**

In [11]:
array_2d = [
    [1, 4, 9],
    [16, 25, 36],
    [49, 64, 81]
]

sqrt_array = []
for row in array_2d:
    new_row = []
    for element in row:
        new_row.append(element ** 0.5)
    sqrt_array.append(new_row)

print(sqrt_array)


[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]


**Question 22**

In [12]:
arr1 = [1, 2, 3, 4, 5]
arr2 = [5, 4, 3, 2, 1]

dot_product = 0
for i in range(len(arr1)):
    dot_product += arr1[i] * arr2[i]

print(dot_product)


35


**Question 23**

In [13]:
arr1 = [5, 2, 8, 4, 9]
arr2 = [3, 6, 7, 4, 10]

comparison = []
for i in range(len(arr1)):
    comparison.append(arr1[i] > arr2[i])

print(comparison)


[True, False, True, False, False]


Question 24

In [14]:
array_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

doubled_array = []
for row in array_2d:
    new_row = []
    for element in row:
        new_row.append(element * 2)
    doubled_array.append(new_row)

print(doubled_array)


[[2, 4, 6], [8, 10, 12], [14, 16, 18]]


**Question 25**

In [15]:
import random

arr = [random.randint(1, 100) for _ in range(100)]

even_sum = 0
for num in arr:
    if num % 2 == 0:
        even_sum += num

print("Array:", arr)
print("Sum of even numbers:", even_sum)


Array: [18, 49, 38, 81, 53, 11, 36, 59, 38, 12, 48, 16, 57, 26, 59, 8, 55, 83, 18, 39, 2, 23, 57, 3, 92, 9, 89, 43, 99, 83, 89, 95, 73, 32, 46, 58, 97, 52, 96, 60, 33, 85, 89, 49, 82, 87, 12, 9, 29, 87, 67, 64, 50, 70, 13, 65, 38, 10, 60, 18, 77, 61, 2, 93, 35, 72, 86, 71, 86, 26, 44, 25, 59, 74, 64, 21, 39, 35, 42, 78, 58, 86, 15, 47, 31, 14, 36, 24, 2, 29, 23, 25, 79, 40, 82, 46, 99, 84, 44, 4]
Sum of even numbers: 2194


# Linear Algebra

**Question 26**

In [19]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

print("Determinant:", determinant)


Determinant: 0


**Question 27**

In [20]:
matrix = [
    [4, 7],
    [2, 6]
]

a, b = matrix[0]
c, d = matrix[1]

det = a*d - b*c

if det == 0:
    print("Matrix is singular, no inverse exists.")
else:
    inverse = [
        [ d/det, -b/det],
        [-c/det,  a/det]
    ]

    identity = [[0, 0], [0, 0]]
    for i in range(2):
        for j in range(2):
            for k in range(2):
                identity[i][j] += matrix[i][k] * inverse[k][j]

    print("Inverse Matrix:", inverse)
    print("Verification (Identity):", identity)


Inverse Matrix: [[0.6, -0.7], [-0.2, 0.4]]
Verification (Identity): [[0.9999999999999998, 4.440892098500626e-16], [-2.220446049250313e-16, 1.0000000000000004]]


**Question 28**

In [21]:
import math

matrix = [
    [4, 2],
    [1, 3]
]

a, b = matrix[0]
c, d = matrix[1]

trace = a + d
det = a*d - b*c

discriminant = trace**2 - 4*det

lambda1 = (trace + math.sqrt(discriminant)) / 2
lambda2 = (trace - math.sqrt(discriminant)) / 2

print("Eigenvalues:", lambda1, lambda2)

def eigenvector(lmbda):
    m = [[a - lmbda, b],
         [c, d - lmbda]]

    if m[0][0] != 0 or m[0][1] != 0:
        v = [ -m[0][1], m[0][0] ]
    else:
        v = [ -m[1][1], m[1][0] ]
    return v

v1 = eigenvector(lambda1)
v2 = eigenvector(lambda2)

print("Eigenvector for λ1:", v1)
print("Eigenvector for λ2:", v2)


Eigenvalues: 5.0 2.0
Eigenvector for λ1: [-2, -1.0]
Eigenvector for λ2: [-2, 2.0]


**Question 29**

In [22]:
import numpy as np

A = np.array([[2, 3],
              [4, 6]])

B = np.array([5, 10])

try:
    X = np.linalg.solve(A, B)
    print("Solution:", X)
except np.linalg.LinAlgError:
    print("The system has no unique solution (matrix is singular).")


The system has no unique solution (matrix is singular).


**Question 30**

In [23]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("Singular values:", S)
print("V^T:\n", Vt)

Sigma = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma, S)

A_reconstructed = U @ Sigma @ Vt
print("Reconstructed A:\n", A_reconstructed)


U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
V^T:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Reconstructed A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
